[36m[2022-06-18 14:22:31 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-18 14:22:31 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-06-18 14:22:31 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-18 14:22:31 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/naveenkumar/.chaostoolkit/settings.yaml'.
[36m[2022-06-18 14:22:31 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-18 14:22:31 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-06-18 14:22:31 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-18 14:22:31 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-06-18 14:22:31 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-06-18 14:22:31 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-18 14:22:31 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-18 14:22:31 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-06-18 14:22:31 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-06-18 14:22:31 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-18 14:22:31 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-18 14:22:31 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-06-18 14:22:31 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-06-18 14:22:31 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-06-18 14:22:31 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-06-18 14:22:31 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-06-18 14:22:31 INFO] [run:320][39m Running experiment: EC2 Delete
[36m[2022-06-18 14:22:31 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-06-18 14:22:31 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-06-18 14:22:31 INFO] [run:348][39m Rollbacks strategy: default
[32m[2022-06-18 14:22:31 INFO] [run:353][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2022-06-18 14:22:31 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[32m[2022-06-18 14:22:31 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-06-18 14:22:31 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-06-18 14:22:31 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-18 14:22:31 INFO] [activity:204][39m Action: stop-an-ec2-instance
[36m[2022-06-18 14:22:31 DEBUG] [python:33][39m Activity 'stop-an-ec2-instance' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-18 14:22:31 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-18 14:22:31 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-18 14:22:32 DEBUG] [actions:70][39m Picked EC2 instance 'defaultdict(typing.List, {'normal': ['i-009e9456ae22df560']})' from AZ 'None' to be stopped
[36m[2022-06-18 14:22:32 DEBUG] [actions:587][39m Stopping instances: ['i-009e9456ae22df560']
[36m[2022-06-18 14:22:33 DEBUG] [activity:221][39m   => succeeded with '[{'StoppingInstances': [{'CurrentState': {'Code': 64, 'Name': 'stopping'}, 'InstanceId': 'i-009e9456ae22df560', 'PreviousState': {'Code': 16, 'Name': 'running'}}], 'ResponseMetadata': {'RequestId': '8e7033ee-dd3f-4bb7-8a0a-ed9bbb948afd', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '8e7033ee-dd3f-4bb7-8a0a-ed9bbb948afd', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '579', 'date': 'Sat, 18 Jun 2022 18:22:39 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-18 14:22:33 INFO] [activity:239][39m Pausing after activity for 20s...
[36m[2022-06-18 14:22:53 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-18 14:22:53 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-18 14:22:53 INFO] [activity:204][39m Action: detach-random-volume
[36m[2022-06-18 14:22:53 DEBUG] [python:33][39m Activity 'detach-random-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-18 14:22:53 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-18 14:22:53 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-18 14:22:54 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 18, 18, 58, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-009e9456ae22df560', 'State': 'detaching', 'VolumeId': 'vol-04a2e97419f337a51', 'ResponseMetadata': {'RequestId': '8a61a556-067e-44bd-92f8-cc7386c2885a', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '8a61a556-067e-44bd-92f8-cc7386c2885a', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 18:22:59 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-18 14:22:54 INFO] [activity:239][39m Pausing after activity for 20s...
[36m[2022-06-18 14:23:14 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-18 14:23:14 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-18 14:23:14 INFO] [activity:204][39m Action: start-instances
[36m[2022-06-18 14:23:14 DEBUG] [python:33][39m Activity 'start-instances' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-18 14:23:14 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-18 14:23:14 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-18 14:23:14 DEBUG] [actions:645][39m Starting normal instance(s): ['i-009e9456ae22df560']
[36m[2022-06-18 14:23:14 DEBUG] [activity:221][39m   => succeeded with '[{'CurrentState': {'Code': 0, 'Name': 'pending'}, 'InstanceId': 'i-009e9456ae22df560', 'PreviousState': {'Code': 80, 'Name': 'stopped'}}]'
[32m[2022-06-18 14:23:14 INFO] [activity:239][39m Pausing after activity for 30s...
[36m[2022-06-18 14:23:44 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-18 14:23:44 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-06-18 14:23:44 INFO] [activity:204][39m Action: attach-volume
[36m[2022-06-18 14:23:44 DEBUG] [python:33][39m Activity 'attach-volume' loaded from '/home/naveenkumar/.local/lib/python3.8/site-packages/chaosaws/ec2/actions.py'
[36m[2022-06-18 14:23:44 DEBUG] [__init__:75][39m Using AWS region 'us-east-2'
[36m[2022-06-18 14:23:44 DEBUG] [__init__:84][39m Client will be using profile 'default' from boto3 session
[36m[2022-06-18 14:23:45 DEBUG] [actions:713][39m Attached volume vol-04a2e97419f337a51 to instance i-009e9456ae22df560
[36m[2022-06-18 14:23:45 DEBUG] [activity:221][39m   => succeeded with '[{'AttachTime': datetime.datetime(2022, 6, 18, 18, 23, 52, 656000, tzinfo=tzutc()), 'Device': '/dev/sdf', 'InstanceId': 'i-009e9456ae22df560', 'State': 'attaching', 'VolumeId': 'vol-04a2e97419f337a51', 'ResponseMetadata': {'RequestId': '2e7330d1-26fb-49f9-9103-23f4f4206c73', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '2e7330d1-26fb-49f9-9103-23f4f4206c73', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '410', 'date': 'Sat, 18 Jun 2022 18:23:52 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}]'
[32m[2022-06-18 14:23:45 INFO] [activity:239][39m Pausing after activity for 10s...
[36m[2022-06-18 14:23:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-06-18 14:23:55 DEBUG] [__init__:399][39m No controls to apply on 'method'
[32m[2022-06-18 14:23:55 INFO] [run:893][39m Let's rollback...
[36m[2022-06-18 14:23:55 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-18 14:23:55 INFO] [rollback:27][39m No declared rollbacks, let's move on.
[36m[2022-06-18 14:23:55 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-06-18 14:23:55 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-06-18 14:23:55 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-06-18 14:23:55 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-06-18 14:23:55 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-06-18 14:24:13 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-06-18 14:24:13 DEBUG] [cli:113][39m Running command 'report'
[36m[2022-06-18 14:24:13 DEBUG] [cli:117][39m Using settings file '/home/naveenkumar/.chaostoolkit/settings.yaml'
[36m[2022-06-18 14:24:13 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-06-18 14:24:13 DEBUG] [caching:35][39m Cached 4 activities
